version: '3.7'
services:
  mysql:
    image: mysql:8.0
    restart: always
    volumes:
      - mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
    command: --default-authentication-plugin=mysql_native_password
  wordpress:
    image: apache-wordpress 
    build: 
      context: .
    restart: "no"
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
      - WORDPRESS_DB_HOST=mysql
      - WORDPRESS_DB_USER=user
      - WORDPRESS_DB_PASSWORD=password
      - WORDPRESS_DB_NAME=exampleDatabase
      - SITE_URL=https://example.test
      - SITE_NAME=example
    volumes:
      - ./wordpress:/var/www/html
    labels:
      - traefik.http.routers.example-wordpress1.entrypoints=web
      - traefik.http.routers.example-wordpress1.rule=Host(
        `example.test`, `www.example.test`)
      - traefik.http.routers.example-wordpress1-secure.tls=true
      - traefik.http.routers.example-wordpress1-secure.entrypoints=web-secure
      - traefik.http.routers.example-wordpress1-secure.rule=Host(
        `example.test`, `www.example.test`)
      - traefik.http.routers.example-wordpress1.middlewares=https
      - traefik.http.middlewares.https.redirectscheme.scheme=https
      - traefik.http.services.service1.loadbalancer.server.port=5000
    depends_on: 
      - mysql
    networks:
      - default
      - traefik
volumes: 
  mysql: {}
networks:
  traefik:
    external: true