version: '3.1'

services:
  mysql:
    image: mysql:5.7
    restart: unless-stopped
    volumes:
      - mysql:/var/lib/mysql
    environment:
      MYSQL_DATABASE: exampledb
      MYSQL_USER: exampleuser
      MYSQL_PASSWORD: examplepass
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
  wordpress:
    image: jamesgreenaway/wordpress:latest
    build: 
      context: .
    restart: unless-stopped
    depends_on: 
      - mysql
    environment:
      WORDPRESS_DB_HOST: mysql
      WORDPRESS_DB_USER: exampleuser
      WORDPRESS_DB_PASSWORD: examplepass
      WORDPRESS_DB_NAME: exampledb
      SSL_SITE_NAME: Wordpress
      LOCAL_UID: 1000
    ports:
      - "5000:443"
      - "8080:80"
    volumes:
     - ./:/var/www/html
volumes: 
  mysql: {}